// import type { Metadata } from "next";
// import {  Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "../Router/Navigation";
import { ReduxProvider } from "../components/redux-proviider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Restaurant App",
  description: "Generated by Pegasus International",
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
          <ReduxProvider>
        <Navigation/>
        {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
